### ISSUE TITLE
deletecomputeridsfromcsv command issue

### ISSUE THREAD

**Issue by benducklow** [eventbrite/Casper-API-Tools#2]
Hello and Happy New Year! Its me again I went to test out another piece from this script and received the following error:

```
$ casper deletecomputeridsfromcsv /Users/me/Desktop/CASPER-API/todeletebyjssid_010317.csv
Password:
Test Run: Delete computer ID 514
Getting computer with JSS ID 514...

GENERAL INFORMATION:
Computer Name: machinename1
Asset Number: None
JSS Computer ID: 514
Serial Number: C02GL1J5XXXX
Mac Address: 3C:07:54:42:2D:F5
Managed: false
Traceback (most recent call last):
  File "/Volumes/CasperAPI/CasperAPI_CLI.py", line 1523, in <module>
    main()
  File "/Volumes/CasperAPI/CasperAPI_CLI.py", line 1439, in main
    deleteComputerIDsFromCSV(computersCSV, user, password)
  File "/Volumes/CasperAPI/CasperAPI_CLI.py", line 1206, in deleteComputerIDsFromCSV
    deleteComputerByID(compID, username, password)
  File "/Volumes/CasperAPI/CasperAPI_CLI.py", line 1166, in deleteComputerByID
    getComputerByID(comp_id, username, password)
  File "/Volumes/CasperAPI/CasperAPI_CLI.py", line 377, in getComputerByID
    print 'Last Check-In: ' + last_contact_time
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

I changed the name of the serial #, but otherwise its what I am receiving after I run the command. Is this another thing I am messing up?

**Comment by jkuo-eb** [comment]
Sorry for the delay looking at this. The trouble here is that the last_contact_time is probably a null string, and the line needs to be changed to read it as a string. 

The affected line would instead need to be:

`print 'Last Check-In: ' + str(last_contact_time)`

**Comment by jkuo-eb** [comment]
Ben, I updated the script to address that issue - can you test it out again?

**Comment by benducklow** [comment]
I don't have the need to delete machines from the JSS very often, but will definitely use this and let you know. It may be several weeks yet. Thanks so much for the taking a look and addressing this!

**Comment by benducklow** [comment]
OK, I confirmed things worked! I like that it it prompts you (so to speak) to confirm you want to delete the record before actually doing it. **NICE WORK!** and thanks for sharing this gem!

**Comment by jkuo-eb** [comment]
Great, thanks for checking on that. I'm glad it's helpful!
